services:
  weather-app:
    image: sole_temperature
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
